name: Run build check
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        name: build check
        steps:
            - uses: actions/checkout@v2
              name: Check out repository
            - uses: actions/setup-node@v1
              name: Set up Node.js
              with:
                  node-version: 22
            - run: |
                  npm ci
                  npm run build
